#!/bin/bash
clear
printf "\033[1;33m"
figlet -c ThanhBinh
figlet -c -f banner Rom2DSU
printf "\033[1;33m"

while getopts f: flag
do
    case ${flag} in
	f) file_rom=${OPTARG};;
    esac
done

echo "File ROM: $file_rom!"
echo "Output: dsu.zip!"
figlet Extracting ROM!!
unzip $file_rom -d ./work_dir
figlet Extracting *dat.br files....
brotli -d ./work_dir/system.new.dat.br ./work_dir/product.new.dat.br ./work_dir/vendor.new.dat.br
figlet Converting.....
sdat2img.py ./work_dir/system.transfer.list ./work_dir/system.new.dat ./work_dir/system.img
sdat2img.py ./work_dir/product.transfer.list ./work_dir/product.new.dat ./work_dir/product.img
sdat2img.py ./work_dir/vendor.transfer.list ./work_dir/vendor.new.dat ./work_dir/vendor.img
clear
mv ./work_dir/system.img ./system.img
mv ./work_dir/product.img ./product.img
mv ./work_dir/vendor.img ./vendor.img
clear
figlet Creating DSU Package......
zip -r ./dsu.zip ./system.img ./product.img ./vendor.img
echo "Create DSU Package successfully! now you can install DSU Package with ADB or DSU Sideloader app!!!"
rm -rf work_dir
rm *.img -f
